version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contratos_api
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production