version: '3.8'

services:
  app:
    image: node:22-alpine
    container_name: contratos_api
    working_dir: /var/lib/docker/volumes/app
    volumes:
      - .:/var/lib/docker/volumes/app
      - node_modules:/var/lib/docker/volumes/app/node_modules   # volume nomeado para node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: sh -c "npm install --legacy-peer-deps && npm run start"

volumes:
  node_modules:    # Criação do volume nomeado
